spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jwt
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
